INSERT INTO Readers (User_id, First_name, Last_name, Email, Address) 
INSERT INTO Phone_number (User_id, Phone_number) 
INSERT INTO Authentication_system (password, login_id) 
INSERT INTO Staff (Staff_id, First_name, Last_name, Email, Phone_no, Login_id) 
INSERT INTO track (Staff_id, User_id) 
INSERT INTO Publisher (Publisher_id, Year_of_Publication, Name) 
INSERT INTO Books (Auth_No, Title, ISBN, Publisher_id, Category, Edition, Price, Staff_id) 
INSERT INTO issue (issue_date, due_date, return_date, pkb, pkr) 
INSERT INTO Report (Reg_id, User_id, Book_No, issue_date, Staff_id) 
INSERT INTO Readers (User_id, First_name, Last_name, Email, Address)
INSERT INTO Readers (User_id, First_name, Last_name, Email, Address)
INSERT INTO Readers (User_id, First_name, Last_name, Email, Address)
INSERT INTO Readers (User_id, First_name, Last_name, Email, Address)
INSERT INTO Readers (User_id, First_name, Last_name, Email, Address)
INSERT INTO Readers (User_id, First_name, Last_name, Email, Address)
INSERT INTO Readers (User_id, First_name, Last_name, Email, Address)
INSERT INTO Readers (User_id, First_name, Last_name, Email, Address)
INSERT INTO Readers (User_id, First_name, Last_name, Email, Address)
INSERT INTO Readers (User_id, First_name, Last_name, Email, Address)
INSERT INTO Phone_number (User_id, Phone_number)
INSERT INTO Phone_number (User_id, Phone_number)
INSERT INTO Phone_number (User_id, Phone_number)
INSERT INTO Phone_number (User_id, Phone_number)
INSERT INTO Phone_number (User_id, Phone_number)
INSERT INTO Phone_number (User_id, Phone_number)
INSERT INTO Phone_number (User_id, Phone_number)
INSERT INTO Phone_number (User_id, Phone_number)
INSERT INTO Phone_number (User_id, Phone_number)
INSERT INTO Phone_number (User_id, Phone_number)
INSERT INTO Phone_number (User_id, Phone_number)
INSERT INTO Phone_number (User_id, Phone_number)
INSERT INTO Phone_number (User_id, Phone_number)
INSERT INTO Authentication_system (password, login_id)
INSERT INTO Authentication_system (password, login_id)
INSERT INTO Authentication_system (password, login_id)
INSERT INTO Authentication_system (password, login_id)
INSERT INTO Authentication_system (password, login_id)
INSERT INTO Authentication_system (password, login_id)
INSERT INTO Authentication_system (password, login_id)
INSERT INTO Authentication_system (password, login_id)
INSERT INTO Authentication_system (password, login_id)
INSERT INTO Authentication_system (password, login_id)
INSERT INTO Authentication_system (password, login_id)
INSERT INTO Authentication_system (password, login_id)
INSERT INTO Authentication_system (password, login_id)
INSERT INTO Staff (Staff_id, First_name, Last_name, Email, Phone_no, Login_id)
INSERT INTO Staff (Staff_id, First_name, Last_name, Email, Phone_no, Login_id)
INSERT INTO Staff (Staff_id, First_name, Last_name, Email, Phone_no, Login_id)
INSERT INTO Staff (Staff_id, First_name, Last_name, Email, Phone_no, Login_id)
INSERT INTO Staff (Staff_id, First_name, Last_name, Email, Phone_no, Login_id)
INSERT INTO track (Staff_id, User_id)
INSERT INTO track (Staff_id, User_id)
INSERT INTO track (Staff_id, User_id)
INSERT INTO track (Staff_id, User_id)
INSERT INTO track (Staff_id, User_id)
INSERT INTO track (Staff_id, User_id)
INSERT INTO track (Staff_id, User_id)
INSERT INTO track (Staff_id, User_id)
INSERT INTO track (Staff_id, User_id)
INSERT INTO track (Staff_id, User_id)
INSERT INTO Publisher (Publisher_id, Year_of_Publication, Name)
INSERT INTO Publisher (Publisher_id, Year_of_Publication, Name)
INSERT INTO Publisher (Publisher_id, Year_of_Publication, Name)
INSERT INTO Publisher (Publisher_id, Year_of_Publication, Name)
INSERT INTO Publisher (Publisher_id, Year_of_Publication, Name)
INSERT INTO Publisher (Publisher_id, Year_of_Publication, Name)
INSERT INTO Publisher (Publisher_id, Year_of_Publication, Name)
INSERT INTO Publisher (Publisher_id, Year_of_Publication, Name)
INSERT INTO Publisher (Publisher_id, Year_of_Publication, Name)
INSERT INTO Publisher (Publisher_id, Year_of_Publication, Name)
INSERT INTO Books (Auth_No, Title, ISBN, Publisher_id, Category, Edition, Price, Staff_id)
INSERT INTO Books (Auth_No, Title, ISBN, Publisher_id, Category, Edition, Price, Staff_id)
INSERT INTO Books (Auth_No, Title, ISBN, Publisher_id, Category, Edition, Price, Staff_id)
INSERT INTO Books (Auth_No, Title, ISBN, Publisher_id, Category, Edition, Price, Staff_id)
INSERT INTO Books (Auth_No, Title, ISBN, Publisher_id, Category, Edition, Price, Staff_id)
INSERT INTO Books (Auth_No, Title, ISBN, Publisher_id, Category, Edition, Price, Staff_id)
INSERT INTO Books (Auth_No, Title, ISBN, Publisher_id, Category, Edition, Price, Staff_id)
INSERT INTO Books (Auth_No, Title, ISBN, Publisher_id, Category, Edition, Price, Staff_id)
INSERT INTO Books (Auth_No, Title, ISBN, Publisher_id, Category, Edition, Price, Staff_id)
INSERT INTO Books (Auth_No, Title, ISBN, Publisher_id, Category, Edition, Price, Staff_id)
INSERT INTO Books (Auth_No, Title, ISBN, Publisher_id, Category, Edition, Price, Staff_id)
INSERT INTO Books (Auth_No, Title, ISBN, Publisher_id, Category, Edition, Price, Staff_id)
INSERT INTO Books (Auth_No, Title, ISBN, Publisher_id, Category, Edition, Price, Staff_id)
INSERT INTO Books (Auth_No, Title, ISBN, Publisher_id, Category, Edition, Price, Staff_id)
INSERT INTO Books (Auth_No, Title, ISBN, Publisher_id, Category, Edition, Price, Staff_id)
INSERT INTO Books (Auth_No, Title, ISBN, Publisher_id, Category, Edition, Price, Staff_id)
INSERT INTO Books (Auth_No, Title, ISBN, Publisher_id, Category, Edition, Price, Staff_id)
INSERT INTO Books (Auth_No, Title, ISBN, Publisher_id, Category, Edition, Price, Staff_id)
INSERT INTO Books (Auth_No, Title, ISBN, Publisher_id, Category, Edition, Price, Staff_id)
INSERT INTO Books (Auth_No, Title, ISBN, Publisher_id, Category, Edition, Price, Staff_id)
INSERT INTO Books (Auth_No, Title, ISBN, Publisher_id, Category, Edition, Price, Staff_id)
INSERT INTO Books (Auth_No, Title, ISBN, Publisher_id, Category, Edition, Price, Staff_id)
INSERT INTO Books (Auth_No, Title, ISBN, Publisher_id, Category, Edition, Price, Staff_id)
INSERT INTO Books (Auth_No, Title, ISBN, Publisher_id, Category, Edition, Price, Staff_id)
INSERT INTO Books (Auth_No, Title, ISBN, Publisher_id, Category, Edition, Price, Staff_id)
INSERT INTO Books (Auth_No, Title, ISBN, Publisher_id, Category, Edition, Price, Staff_id)
INSERT INTO Books (Auth_No, Title, ISBN, Publisher_id, Category, Edition, Price, Staff_id)
INSERT INTO Books (Auth_No, Title, ISBN, Publisher_id, Category, Edition, Price, Staff_id)
INSERT INTO Books (Auth_No, Title, ISBN, Publisher_id, Category, Edition, Price, Staff_id)
INSERT INTO Books (Auth_No, Title, ISBN, Publisher_id, Category, Edition, Price, Staff_id)
INSERT INTO issue (issue_date, due_date, return_date, pkb, pkr)
INSERT INTO issue (issue_date, due_date, return_date, pkb, pkr)
INSERT INTO issue (issue_date, due_date, return_date, pkb, pkr)
INSERT INTO issue (issue_date, due_date, return_date, pkb, pkr)
INSERT INTO issue (issue_date, due_date, return_date, pkb, pkr)
INSERT INTO issue (issue_date, due_date, return_date, pkb, pkr)
INSERT INTO issue (issue_date, due_date, return_date, pkb, pkr)
INSERT INTO issue (issue_date, due_date, return_date, pkb, pkr)
INSERT INTO issue (issue_date, due_date, return_date, pkb, pkr)
INSERT INTO issue (issue_date, due_date, return_date, pkb, pkr)
INSERT INTO issue (issue_date, due_date, return_date, pkb, pkr)
INSERT INTO issue (issue_date, due_date, return_date, pkb, pkr)
INSERT INTO issue (issue_date, due_date, return_date, pkb, pkr)
INSERT INTO issue (issue_date, due_date, return_date, pkb, pkr)
INSERT INTO issue (issue_date, due_date, return_date, pkb, pkr)
INSERT INTO Report (Reg_id, User_id, Book_No, issue_date, Staff_id)
INSERT INTO Report (Reg_id, User_id, Book_No, issue_date, Staff_id)
INSERT INTO Report (Reg_id, User_id, Book_No, issue_date, Staff_id)
INSERT INTO Report (Reg_id, User_id, Book_No, issue_date, Staff_id)
INSERT INTO Report (Reg_id, User_id, Book_No, issue_date, Staff_id)
INSERT INTO Report (Reg_id, User_id, Book_No, issue_date, Staff_id)
INSERT INTO Report (Reg_id, User_id, Book_No, issue_date, Staff_id)
INSERT INTO Report (Reg_id, User_id, Book_No, issue_date, Staff_id)
INSERT INTO Report (Reg_id, User_id, Book_No, issue_date, Staff_id)
INSERT INTO Report (Reg_id, User_id, Book_No, issue_date, Staff_id)
INSERT INTO Report (Reg_id, User_id, Book_No, issue_date, Staff_id)
INSERT INTO Report (Reg_id, User_id, Book_No, issue_date, Staff_id)
INSERT INTO Report (Reg_id, User_id, Book_No, issue_date, Staff_id)
INSERT INTO Report (Reg_id, User_id, Book_No, issue_date, Staff_id)
INSERT INTO Report (Reg_id, User_id, Book_No, issue_date, Staff_id)
    INSERT INTO Readers (User_id, First_name, Last_name, Email, Address)
    INSERT INTO issue (issue_date, due_date, pkb, pkr)
    INSERT INTO Report (Reg_id, User_id, Book_No, issue_date, Staff_id)
    INSERT INTO Report (Reg_id, User_id, Book_No, issue_date, Staff_id)